apiVersion: v1
kind: Service
metadata:
  name: user-service-db
spec:
  selector:
    app: user-service-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP 