apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  postgres-user: dXNlcl9zZXJ2aWNlX3Byb2Q=  # user_service_prod
  postgres-password: Y2hhbmdlX3RoaXNfaW5fcHJvZHVjdGlvbg==  # change_this_in_production
  postgres-db: dXNlcl9zZXJ2aWNlX3Byb2Q=  # user_service_prod
  secret-key: Y2hhbmdlX3RoaXNfaW5fcHJvZHVjdGlvbl90b19hX3NlY3VyZV9rZXk=  # change_this_in_production_to_a_secure_key 